# Generated by Django 4.1.3 on 2022-12-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libAdmin', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_data', models.DateField()),
                ('authors', models.ManyToManyField(to='libAdmin.author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libAdmin.publisher')),
            ],
        ),
    ]
