# Generated by Django 4.1.3 on 2022-12-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libAdmin', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('r', 'Review'), ('p', 'PUblished')], default='d', max_length=1),
        ),
    ]
